DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `user_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '帐号，用户名',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
  `real_name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `phone` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '电话号码',
  `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `ip` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '上次登录ip',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建人用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新人用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx_username` (`user_name`),
  KEY `idx_phone` (`phone`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_role`;
CREATE TABLE `t_role` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_permission`;
CREATE TABLE `t_permission` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '权限名',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
  `parent_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '父权限ID',
  `parent_name` VARCHAR (60) NOT NULL DEFAULT 0 COMMENT '父权限名称',
  `url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'url',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_user_role`;
CREATE TABLE `t_user_role` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
  `user_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '帐号，用户名',
  `role_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色id',
  `role_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '角色名',
  `role_desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_role_permission`;
CREATE TABLE `t_role_permission` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `role_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色id',
  `role_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '角色名',
  `role_desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '角色描述',
  `permission_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '权限id',
  `permission_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '权限名称',
  `permission_desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
  `url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'url',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_group`;
CREATE TABLE `t_group` (
  `id` BIGINT(20) AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '组名',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '组描述',
  `enable` bit(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` varchar(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` varchar(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `t_env`;
CREATE TABLE `t_env` (
  `id` BIGINT(20) AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '环境名称',
  `description` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '环境描述',
  `creator` VARCHAR(100) NOT NULL DEFAULT 'admin' COMMENT '创建人用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `t_app`;
CREATE TABLE `t_app` (
  `id` BIGINT(20) AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'APP名称',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'APP描述',
  `emails` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱列表逗号分隔',
  `group_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '组id',
  `group_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '组名',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx_group_app_name` (`group_name`,`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `t_config`;
CREATE TABLE `t_config` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `config_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '配置名称',
  `config_desc` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '配置描述',
  `type` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '0:配置文件 ，1:配置项',
  `type_desc` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '配置文件 || 配置项',
  `value` MEDIUMTEXT DEFAULT NULL COMMENT '配置的值',
  `version` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '版本号',
  `app_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT 'APP id',
  `app_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'APP 名称',
  `group_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '组id',
  `group_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '组名',
  `env_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '环境id',
  `env_name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '环境名称',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idx_group_name_config` (`group_name`,`app_name`,`config_name`)

) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;


DROP TABLE IF EXISTS `t_config_history`;
CREATE TABLE `t_config_history` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `config_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT 'config id',
  `config_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '配置名称',
  `new_value` MEDIUMTEXT DEFAULT NULL COMMENT '新的值',
  `old_value` MEDIUMTEXT DEFAULT NULL COMMENT '旧的值',
  `type` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '0:配置文件 ，1:配置项',
  `type_desc` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '配置文件 || 配置项',
  `version` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '版本号',
  `app_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'APP id',
  `app_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'APP 名称',
  `group_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '组id',
  `group_name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '组名',
  `env_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '环境id',
  `env_name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '环境名称',
  `enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否可用',
  `creator` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '创建用户名',
  `updater` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '更新用户名',
  `create_time` DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'  ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;